# Builds and uploads latest commit to gh-pages

name: Nightly Build

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant permissions to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Set destination/branch property
        run: echo "destination=files/nightly/${GITHUB_REF##*/}" >> nightly.properties

      - name: Read destination property to var
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './nightly.properties'
          property: 'destination'

      - name: Upload to branch specific dir
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/libs
          destination_dir: ${{ steps.read_property.outputs.value }}

      - name: Upload to latest dir
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/libs
          destination_dir: files/nightly/latest
